*! Mar22'26

capture program drop genyhatsP					// Originally `genyhats', in Version 2 is called by `stackmeWrapper'

program define genyhatsP				
												// In v2 stackmeWrapper extracts working data before calling `cmd'P, afterwards 
												// merging the results back into the origial dataset
*set trace off
  
*! gendyhatsP version 2 for Stata version 9.0 (2/23/23 by Mark) has options cumulating as extra varlists are processed 
*! Minor tweaks Nov'24 to handle revised weighting strategy.

	// This is a rewrite of the version 1.5 genyhats (the version that processed multiple varlists, using byable code), 
	// renamed genyhatsP to make it callable from the version 2.0 stackMe wrapper (itself called from genyhats.ado).
	//    The stackmeWrapper calls genyhatsP once for each data context. It has added sevaral options tp the original
	// call that transmit information acquired by the wrapper that was previously supplied within this program. Option 
	// `extradiag' is now a standard stackMe option determining the verbosity of the output. Option `quietly' replaces 
	// the previous `outmode' local governing this verbosityt. Option `prefix' tells genyhatsP whether the `opt1' 
	// processed by the wrapper was supplied as a prefix to the depvarlist rather than as an option.
	//    CRITICALLY, the presence or absence of a prefix to the depvarlist determines whether yhats are produced
	// by bivariate or multivariate analyses (multivariate if the depvar is supplemented by the prefix or if optioned).
	

																// genyhats-specific lines of code are suffixed with "**"
																
																
	
	version 16.1							// (0) genyhatsP version 2 preliminaries

	
	
*****************
capture noisily {												// introduces codeblocks within which any error will be captured 
*****************



																//(will be handled after the close capture brace
	syntax anything(id="varlist") [if][in][aw fw iw pw],[DEPvarname(varname) CONtextvars(varlist) ITEmname(varname) LOGit]  ///
	[ DPRefix(string) IPRefix(string) APRefix(string) MULtivariate ] ///
	[ REPlace prfx(string) ADJust(string) EFFects(string) EFOrmat(string) limitdiag(integer -1) EXTradiag NODIAg ]			///
	[ NOCONtexts NOSTAcks nvarlst(integer 1) ctxvar(string) nc(integer 0) c(integer 0) wtexplst(string) * ] 
	
//  USING STRING PREFIX TO INPUT VAR:
*	AN OUTCOME NAME GENERATED BY A `cmd'P SUBPROGRAM WILL HAVE AS INTERIM PREFIX THE INITIAL DIFFERENTIATING THE VAR FROM OTHER VARS	***
*	GENERATED BY THAT SUBPROGRAM. IN 'cleanup' THAT PREFIX WILL BE REPLACED ACCORDING TO USER OPTION AND EXTENDED BY PREPENDING THE
*	COMMAND-SPECIFIC PREFIX FOR THIS COMMAND ('y' FOR 'genyhats'). THE `cmd'P SUBPROGRAM MAY WANT TO EMULATE THAT PREFIX FOR DIATNOSTIC
*	DISPLAY PURPOSES.
	
																// NOTE THAT FINAL `wtexplst' WILL REPLACE [aw...], if any, below
																// Additionally, global multivariate was initialized in wrapper
	
																// Wrapper adds optns following limitdiag
																// NOTE THAT prfx and `isprfx' are absent 'cos redundant				**
global errloc "genyh(1)"
	
	
	

											// (1) deal with options (these are the same for all varlists in set)
											
	global multivariate = "`multiveriate'"  					// Global will tell 'predcen' what user optioned
	
	local isprfx = ""											// By default there is no prefix, so not a multivariate analysis
																// (unless `multivariate' was optd (now in $multivariate))
	if (`limitdiag' == -1)  local limitdiag = .					// Make that a very large number
	if ("`extradiag'"!="")  local limitdiag = .					// Ditto
	if (`limitdiag' == 0)	local quietly = "quietly"
	else  {														// Else `extradiag' is empty
		if `limitdiag'<=`c'  local limitdiag = 0				// And `limitdiag' becomes =0 if  `c' is >=`limitdiag'
	}
	
/*	if `c'==1  {												// MOVE THIS CODEBLOCK TO genyhatsO WHEN IMPLEMENTED				***
		local apr = "_"											// By default `apr' contains just the final "_" of var prefix
		if "`aprefix'"!=""  local apr = "`aprefix'"				// If `aprefix' was optioned it replaces that "_"
																// `genyhats' AND EVENTUALLY OTHERS USE OUTCOME NAMES NOT INTERIMS	***
		if substr("`dprefix'",-1,1)=="_"  local dprefix = substr("`dprefix'",1,strlen("`dprefix'")-1)
		local dpr = "d`apr'"									// By default `dpr' is "d" followed by `apr' (usually just "_")
		if "`dprefix'"!="" local dpr = "`dprefix``apr'"			// If a different `dprefix' was optioned, it replaces the "d"
	
		if substr("`iprefix'",-1,1)=="_"  local iprefix = substr("`iprefix'",1,strlen("`iprefix'")-1)
		local ipr = "i`apr'"									// Ditto for `ipr'
		if "`iprefix'"!=""  local ipr = "`iprefix'`apr'"
*	}	
*/																// WEIGHT IS APPLIED SEPARATELY FOR EACH nvarlst, below
	if "`adjust'"!=""  {
	   local cen = substr("`adjust'",1,3)						// Require only 1st 3 chars of keyword								***
	   foreach str in "mea con no"  {
		  if "`cen'"!="`str'"  continue							// If not matched continue with next str
		  local `cen' = "`str'"				
		  continue, break										// Break out of loop if found a match
	   }	
	} //endif
	
	else  local cen = "null"									// Seemingly need to initialize this local even if empty
			
	if `c'==1  {
			
	  if (`limitdiag'!=0 & `c'==1) { 							// display for first context if optioned
		local contextlabel : label lname `c'					// Retrieve the label for this context built by _mkcross			**
		noisily display "Y-hats will be separately generated by context (and stack)" _continue
		if "`extradiag'"!="" noisily display "(starting with {result:`contextlabel'})" _newline
	  }
	  else display " " _newline
	  
	} //endif `c'==1
																// All of the above is overhead repeatd for each `cmd'P 

				
				
				
pause genyh(2)				
global errloc "genyh(2)"

				
				
				
											// (2) HERE STARTS PROCESSING OF CURRENT CONTEXT . . .
											
			
	quietly count 	
	local numobs = r(N)											// N of observations in this context
			
																// Whether or not `multivariate' was optiond, that opt can be overriddn
	forvalues nvl = 1/`nvarlst'  {						 		// Cycle thru varlists included in possible multivarlist
																// (default prefix is in option `depvarname')
		 local isprfx = ""										// Flag tells 'predcent' if this is a multivariate analysis
		 local dvar = "`depvarname'"							// `dvar' is local version of (prhps optd) `depvarname', which is default
		 local prfxvar = PRFXVARS`nvl'							// Retrieve any prefixvar from relevant scalar primed before wrapper(3)
		 
		 if "`prfxvar'"!="" & "`prfxvar'"!="."  {				// If prefixvar is non-empty/non-missing this is a multivariate analysis
		   local dvar = "`prfxvar'"								// (if there was a yd_ prefix, depvar is in scalar; else use optd vrsion)
		   local isprfx = "yes"									// If there is a prefixvar then this is a multivariate genyhats
/*		   local prfxstr = PRFXSTRS`nvl'						// Retrieve string prefix to that var, if any
		   if "`prfxstr'"!=""  {								// COMMENTED OUT 'COS HAPPENS IN 'cleanup'								***
		   	  if "`prfxstr'"=="yh"  local prfxstr = "y"
		   	  local dpr = "`prfxstr'`apr'"						// If `prfxstr' is not empty, override any existing `dpr' (set above)
		   } //endif `prfxstr'
*/		   
		 } //endif `prfxvar'									// Else will generate bivariate yhats (unless user optn overode default)
																// SEEMINGLY A LOT OF REDUNDANCY ABOVE									***
						   							
		 local indepvars = VARLISTS`nvl'

		 if `c'==1  {				 							// Display these diagnostcs while processng 1st contxt					**
		   if `limitdiag' !=0 & `c'<=`limitdiag'   {			// (or for all contexts if extradiag was optioned)														
			 if "`multivariate'"==""  { 	   					// If analysis will produce multiple bivariate yhats
			   noisily display "Regressing {bf:`dvar'} separately on (each) y`ipr'-prefixed {bf:`indepvars'}; `nostacks' `nocontexts'"
			 }
			 else  {											// Else analysis will produce one multivariate yhat
			   noisily display _newline ///
				 "Regressing `dvar' on `indepvars', saving Y-hat in {result:y`dpr'dvar}; `nostacks' `nocontexts'"
			 } //endelse
		   } //endif `limitdiag'
		 } // endif `c'==1																												**
				
				
		 if "`wtexplst"!=""  {									// Now see if weight expression is not empty in this context
																// (`wtexp' is not taken from [aw...] expression but from final option)
			local wtexp = word("`wtexplst'",`nvl')				// Obtain local name from list to address Stata naming problem
			if "`wtexp'"=="null"  local wtexp = ""
				 
			if "`wtexp'"!=""  {									// If 'wtexp' is not empty (don't non-existant weight)
				local wtexp = subinstr("`wtexp'","$"," ",.)		// Replace all "$" with " "
			}
			
		 } //endif 'wtexplst'
		
		
	
	
	
		
		
global errloc "genyh(3)"
pause 	
	
	
	

											// (3) Heavy lifting is done in program predcent (below)
											
set tracedepth 5
*		 ********
		 predcent `indepvars' `wtexp', depvarname(`dvar') cen(`cen') isprfx(`isprfx') logit(`logit') limitdiag(`limitdiag') nvl(`nvl') ///
				   dpr("`dpr'") ipr("`ipr'")
*		 ********												// Code for called program follows code for this one

set tracedepth 4
				


				
				
				
				
global errloc "genyh(4)"




											// (4) Post-process the results, if optioned
											
					
		 if ("`effects'"!="" & "`effects'"!="no") {				// I DON'T KNOW HOW TO TIDY THE OUTPUT								***

			local usefile = ""
			if ("`effects'"!="window") {
				local usefile = "using `yhat'.`effects'"
			}

			else {
				quietly display "{p_end}" _continue
			}

			if ("`logit'"=="logit") {							// Logit analysis
				local cellfmt = "z(fmt(3) star)"
				if ("`efmt'"!="") {
					local cellfmt = "`efmt'"
				}
				esttab `usefile', cells("`cellfmt'") pr2(%8.3f) mtitles replace compress wide onecell plain label
			}

			else {												// Regression analysis
			
				local cellfmt = "z(fmt(3) star)"
				if ("`efmt'"!="") {
					local cellfmt = "`efmt'"
				}

				if ("`efmt'"=="beta") {
					esttab `usefile', beta(%8.3f) not constant star ar2(%8.3f) mtitles replace compress wide onecell plain label
				}

				else {
					esttab `usefile', cells("`cellfmt'") ar2(%8.3f) constant mtitles replace compress wide onecell plain label
				}

			} //end else

		 } //endif `effects'
	
	


global errloc "genyh(5)"
	
											// (5) Break out of `nvl' loop if `postpipes' is empty
											// 	   (or pre-process syntax for next varlist) COMMENTED OUT `COS NOW USING SCALARS

/*		 if "`postpipes'"==""  continue, break					// Break out of `nvl' loop if `postpipes' is empty 
																// Else ...
		 local anything = strltrim(substr("`postpipes'",3,.))	// Strip leading "||" and any blanks from head of `postpipes'
*/																// (`anything' now contains next varlist and any later ones)
		 local isprfx = ""										// Switch off the prefix flag if it was on

				   
				   
	} //next `nvl' 												// (next list of vars having same options)
				
/*	if $exit==0 {												// COMMENTED OUT COS NOW DONE IN WRAPPER
		if (`nc' > 1 &`limitdiag'!=0  &`c'<`limitdiag') { 	// Display diagnostics, if optioned
			noisily display _newline "Context {result:`c'} ({result:`contextlabel'}) has `numobs' cases"
		}
	}
*/			


	local skipcapture = "skip"									// If this command is executed then there were no errors above


	
* *************
capture } //end capture											// CAPTURE ADDRESSES "not a valid command" ERROR
* *************



if _rc & "`skipcapture'"==""  {

	errexit "Stata has diagnosed a program error"
	exit _rc

} //endif _rc
			

capture }														// STATA DID NOT FIND CLOSING BRACES – DK WHY				***
																// (all braces are balanced according to me)
																
															
end genyhatsP



******************************************************** END genyhatsP ********************************************************





***************************************************** SUBROUTINE predcent *****************************************************



capture program drop predcent  				
											

program define predcent   					// Program to predict and center variable(s) on their means/constants

	version 9.0

	syntax varlist [aw fw iw pw] , depvarname(varname) cen(string) [ logit(str) isprfx(str) extradiag(str) nvl(integer 0) ] ///
								   [ dpr(str) ipr(str) * ]
								   
								 
								 
		
global errloc "predcent"
	
	
	
*****************
capture noisily {											// introduces codeblocks within which any error will be captured 
*****************


	if "`isprfx'"!=""  local multivariate = "yes"			// `isprfx' was established in caller

	local varlist = VARLISTS`nvl'							// (same as in `varlist' if analysis is not multivariate)
	
	if "`cen'"=="null"  local cen = ""						// Argument cannot travel as an empty string; should be absent
	
	if "`weight'"!="" local wt = "[`weight'`exp']"
	if "`extradiag'"==""  local quietly = "quietly"			// By default `quietly' is empty

	local dvar = "`depvarname'"								// Default user-optioned depvar
	if  PRFXVARS`nvl'!=""  local dvar = PRFXVARS`nvl'		// Override with varname found in var(list) that preceed a colon

	if "`multivariate'"!=""  {								// If this varlist is multivariate (whether optioned or string-prefixed)..
	
		local yhat = "m_`dvar'"								// For multivariate yhat there can only be one outcomename in this `nvl'
															// (WE USE `outcmnames' SINCE NAME CAN CHANGE FROM VARLIST TO VARLIST)
*		global interims = "`yhat'"							// For multivariate yhats the interim is the outcmname
															// AS FOR OTHER `cmd's W' VARLIST-SPECIFIC OUTCOMES, PUT IN GLOBAL – NOT! ***
		
		capture quietly generate `yhat' = .					// By default make the yhat missing

		if "`logit'"==""  {									// If `logit' was NOT optioned ...
*			*******************************************		// Initiate a regression analysis
			`quietly' capture reg `dvar' `varlist' `wt'		// `quietly' is effected unless `extradiag' was optioned above
*			*******************************************
			local rc = _rc									// Save RC in local for use below
		}
		
		else  {												// Else `logit' was optioned
*			********************************************
			`quietly' capture logit `dvar' `varlist' `wt' 	// `quietly' is effected unless `extradiag' was optioned above
*			*********************************************	// COMMENTED OUT 'COS DONT WANT 'logit' CMD TWICE
			local rc = _rc									// If insufficient obs or other error, leave result missing
		}

		if `rc'==0  {										// If there are sufficient cases for this analysis
		
			tempvar NN			
			quietly predict `NN'							// Tempvar holds prediction that will replace `yhat'
			quietly replace `yhat' = `NN'

			if "`cen'"!=""  {								// If centering was optioned ...
				if "`cen'"=="con" {
					local adj =_b[_cons]					// Adjust by subtracting constant if optioned
				}											// (both _b and _cons are system _variables (see 'help _variables'))

				else  {										// Else subtract mean ...
					quietly sum `yhat' `wt', meanonly		// Need weighted mean of the `yhat'
					local adj = r(mean)
				}

				if "`logit'"==""  {							// If logit flag is empty..
					quietly replace `yhat' = `yhat' - `adj' // This is a regression adjustment (straightforward)
				}											

				else  {					
					tempvar exponNN							// Else this is a logit adjustment ...
					qui gen `exponNN' = logit(`yhat')
					if "`cen'"=="con"  {
						replace `yhat' = invlogit(expon`NN'-_b[_cons])
					}										// (both _b and _cons are system _variables (see 'help _variables'))

					else  {									// Need weighted mean of the logit(`yhat')
						quietly sum `exponNN' `wt', meanonly 
						quietly replace `yhat' = invlogit(`exponNN'-r(mean))
						capture drop `exponNN'
					}

				} //end else logit adjustment

			} //endif centering

			drop `NN'
				
		} //endif _rc
		
		
		else  {												// Else there was a non-zero return code
		
			if `rc'==2000  {
				scalar NOOBS = NOOBS + " `nvl'"
			}
			else  {
				errexit, msg("Stata reports error `rc' from command $cmd") rc(`rc')
				exit 1
			}
		}

	} //endif $multivariate


		
	else  {											 		// This is a multiple bivariate analyses: one analysis for each indep
			
		local nl = wordcount("`varlist'")					// N of vars found by 'syntax' (same as in VARLISTS`nvl' pre-wraooer(3))

		forvalues i = 1/`nl'  {
			
			local iname = word("`varlist'",`i')				// (and initialized in the same order)
			local yhat = "b_`iname'"						// Standard interim has just the initial letter of cmdname as prefix
			capture quietly generate `yhat' = .				// By default make the yhat missing

			if "`logit'"==""  {								// If `logit' was NOT optioned ...
				capture `quietly' reg `dvar' `iname' `wt'
				local rc = _rc								// If insufficient obs or other error, leave result missing
			}

			else {											// Else `logit' was optioned
				capture `quietly' logit `dvar' `iname' `wt'
				local rc = _rc								// If insufficient obs or other error, leave result missing
			}
				
			if `rc'==0  {									// If sufficient cases for this analysis

				tempvar NN									// Tempvar holds predictions that will replace `yhat's
				quietly predict `NN'
				quietly replace `yhat' = `NN'

				if "`cen'"!=""  {							// If centering was optioned ...
					if "`cen'"=="con"  {
						local adj = _b[_cons]				// Adjust by subtracting constant if optioned
					}

					else  {									// Else subtract mean ...
						qui sum `yhat' `wt'	, meanonly		// Need weighted mean of the yhaat
						local adj = r(mean)
					}

					if "`logit'"==""  {
						quietly replace `yhat'=`yhat'-`adj' // This is a regression adjustment (straightforward)
					}											

					else  {					
						tempvar exponNN						// Else this is a logit adjustment ...
						qui gen `exponNN' = logit(`yhat')
						
						if "`cen'"=="con"  {
							replace `yhat' = invlogit(expon`NN'-_b[_cons])
						}									// (both _b and _cons are system _variables (see 'help _variables'))

						else  {								// Need weighted mean of the logit(`yhat')					***
							quietly sum `exponNN' `wt', meanonly 
							quietly replace `yhat' = invlogit(`exponNN'-r(mean))
						}
						
						capture drop `exponNN'

					} //end else logit adjustment

				} //endif centering

				drop `NN'

			} //endif _rc

		} //next `iname'

	} //end else bivariate
	
	
	local skipcapture = "skip"
	
	
	
* *************
} //end capture
* *************



if _rc & "`skipcapture'"!=""  {
	
	errexit "Stata has diagnosed a program error in genyhats' 'predcen'"
	exit _rc
}

	
	
	
end predcent



***************************************************** END SUBROUTING predcent **************************************************
